### PR TITLE
Make compatible with Jupyterlab 4

### PR DESCRIPTION
**Pull request by mctoohey**
Fixes https://github.com/jupyterlab-contrib/jupyterlab-favorites/issues/14

These changes will not be compatible with Jupyterlab<4

I'm not sure how you want to proceed. Happy to just leave this MR open and continue to maintain it until there is an official release of Jupyterlab 4.0

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks @mctoohey - typically I'll wait for JupyterLab 4.0.0-beta that will have API frozen before merging an upgrade in the main branch.

**Comment by mctoohey** [comment]
@fcollonval Can we look to merge this in now that Jupyterlab 4.0 has been release? The test_isolated step is failing due to what I believe to be a bug in jupyterlab.browser_check. I will open a PR in that repo for that issue.

**Comment by mctoohey** [comment]
Was able to fix the failing test by switching from `--no-chrome-check` to `--no-browser-check` which is functional the same.

**Comment by kevinjohncutler** [comment]
Super excited to see this almost done, really appreciate it!

**Comment by kevinjohncutler** [comment]
@fcollonval Is the extension ready for a pypi release with these changes? I have not been able to get a local install to complete.

**Comment by kamranesmaeili** [comment]
Thanks @fcollonval, same question as @kevinjohncutler here. Any plan regarding the pypi release?

**Comment by mctoohey** [comment]
> Thanks @mctoohey 
> 
> If it is ok with you I'll build on top of this PR to modernize the code and fix the CI.

Thanks for following up on this @fcollonval and fixing the build!

**Pull request merged**
